version: "3.1"
services:
    php:
        container_name: wordpress
        build:
            context: ../
            dockerfile: .docker/Dockerfile
        image: wordpress:latest
        networks:
            - wordpress-net
        volumes:
            - ../:/usr/share/app
        environment:
            - ENVIRONMENT=development
    nginx:
        container_name: wordpress-nginx
        image: nginx
        restart: always
        networks:
            - wordpress-net
        links:
            - mysql
            - php
        depends_on:
            - mysql
            - php
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./etc/nginx/servers:/etc/nginx/servers
            - ../:/usr/share/app
    mysql:
        image: mysql
        env_file:
            - ./.env
        depends_on:
            - php
        ports:
            - "3306:3306"
        networks:
            - wordpress-net
        expose:
            - '3306'
        volumes:
            -  ./data/mysql:/var/lib/mysql
networks:
    wordpress-net: {}